# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_nu_lognu0 <- function(nu, nu0, rho) {
    .Call('_QRSIDE_sum_nu_lognu0', PACKAGE = 'QRSIDE', nu, nu0, rho)
}

cal_nu_entropy <- function(nu, rho) {
    .Call('_QRSIDE_cal_nu_entropy', PACKAGE = 'QRSIDE', nu, rho)
}

ud_loglambda_mu <- function(Xmij, Ni, Lambdaj, pibmu) {
    .Call('_QRSIDE_ud_loglambda_mu', PACKAGE = 'QRSIDE', Xmij, Ni, Lambdaj, pibmu)
}

ud_nu0 <- function(nu, rho) {
    .Call('_QRSIDE_ud_nu0', PACKAGE = 'QRSIDE', nu, rho)
}

cal_mu_m <- function(m, rho, nu, delta) {
    .Call('_QRSIDE_cal_mu_m', PACKAGE = 'QRSIDE', m, rho, nu, delta)
}

cal_bmu <- function(beta, mu_m) {
    .Call('_QRSIDE_cal_bmu', PACKAGE = 'QRSIDE', beta, mu_m)
}

cal_b2mu <- function(beta2, rho, nu, delta2) {
    .Call('_QRSIDE_cal_b2mu', PACKAGE = 'QRSIDE', beta2, rho, nu, delta2)
}

ud_pi <- function(invLambda, loglambda_mu, bmu, b2mu, pi0) {
    .Call('_QRSIDE_ud_pi', PACKAGE = 'QRSIDE', invLambda, loglambda_mu, bmu, b2mu, pi0)
}

ud_Lambda <- function(loglambda_mu, loglambda_s2, pi, bmu, b2mu) {
    .Call('_QRSIDE_ud_Lambda', PACKAGE = 'QRSIDE', loglambda_mu, loglambda_s2, pi, bmu, b2mu)
}

ud_nu <- function(pi, invLambda, loglambda_mu, nu, beta, beta2, m, rho, delta, delta2, nu0) {
    invisible(.Call('_QRSIDE_ud_nu', PACKAGE = 'QRSIDE', pi, invLambda, loglambda_mu, nu, beta, beta2, m, rho, delta, delta2, nu0))
}

ud_m <- function(pi, loglambda_mu, nu, beta, beta2, m, rho, delta) {
    invisible(.Call('_QRSIDE_ud_m', PACKAGE = 'QRSIDE', pi, loglambda_mu, nu, beta, beta2, m, rho, delta))
}

ud_delta <- function(pi, loglambda_mu, nu, beta, beta2, m, rho, delta) {
    invisible(.Call('_QRSIDE_ud_delta', PACKAGE = 'QRSIDE', pi, loglambda_mu, nu, beta, beta2, m, rho, delta))
}

cal_Dmat <- function(pi, loglambda_mu, invLambda, m, rho, nu, delta, mu_m, t, k, k_) {
    .Call('_QRSIDE_cal_Dmat', PACKAGE = 'QRSIDE', pi, loglambda_mu, invLambda, m, rho, nu, delta, mu_m, t, k, k_)
}

ud_beta <- function(pi, loglambda_mu, invLambda, m, rho, nu, delta, mu_m) {
    .Call('_QRSIDE_ud_beta', PACKAGE = 'QRSIDE', pi, loglambda_mu, invLambda, m, rho, nu, delta, mu_m)
}

calELBO <- function(N, X_m, rho, T, loglambda_mu, loglambda_s2, Lambda, invLambda, pi, pi0, beta, beta2, nu, nu2, nu0, mu_m, delta, delta2) {
    .Call('_QRSIDE_calELBO', PACKAGE = 'QRSIDE', N, X_m, rho, T, loglambda_mu, loglambda_s2, Lambda, invLambda, pi, pi0, beta, beta2, nu, nu2, nu0, mu_m, delta, delta2)
}

DeconvMarker <- function(X_m, rho, T, beta, delta, pi, pi0, Lambda, m, max_iter = 100L, eps = 1e-5, verbose = TRUE) {
    .Call('_QRSIDE_DeconvMarker', PACKAGE = 'QRSIDE', X_m, rho, T, beta, delta, pi, pi0, Lambda, m, max_iter, eps, verbose)
}

